server:
  port: 9096
mongock:
  change-logs-scan-package:
    - com.julesn.uabrewwarehouse.migration
spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:warehouse}
      username: ${MONGODB_USER:Kharkiv_student}
      password: ${MONGODB_PASS:Glory_to_Ukraine}